"""add birthday

Revision ID: af20a1fce09f
Revises: b40deced9f08
Create Date: 2023-09-02 15:04:54.898120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af20a1fce09f'
down_revision = 'b40deced9f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_actors_birthday'), ['birthday'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actors_birthday'))
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
